package io.github.hellocuriosity.compose.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

@Suppress("MagicNumber", "LongParameterList")
data class ColorScheme(
    val primary: Color = Color(0xFF6750A4),
    val onPrimary: Color = Color(0xFFFFFFFF),
    val primaryContainer: Color = Color(0xFFEADDFF),
    val onPrimaryContainer: Color = Color(0xFF21005D),
    val secondary: Color = Color(0xFF625B71),
    val onSecondary: Color = Color(0xFFFFFFFF),
    val secondaryContainer: Color = Color(0xFFE8DEF8),
    val onSecondaryContainer: Color = Color(0xFF1D192B),
    val tertiary: Color = Color(0xFF7D5260),
    val onTertiary: Color = Color(0xFFFFFFFF),
    val tertiaryContainer: Color = Color(0xFFFFD8E4),
    val onTertiaryContainer: Color = Color(0xFF31111D),
    val error: Color = Color(0xFFB3261E),
    val onError: Color = Color(0xFFFFFFFF),
    val errorContainer: Color = Color(0xFFF9DEDC),
    val onErrorContainer: Color = Color(0xFF410E0B),
    val background: Color = Color(0xFFFFFBFE),
    val onBackground: Color = Color(0xFF1C1B1F),
    val surface: Color = Color(0xFFFFFBFE),
    val onSurface: Color = Color(0xFF1C1B1F),
    val surfaceVariant: Color = Color(0xFFE7E0EC),
    val onSurfaceVariant: Color = Color(0xFF49454F),
    val outline: Color = Color(0xFF79747E),
    val scrim: Color = Color(0xFF000000),
    val primaryDark: Color = Color(0xFFD0BCFF),
    val onPrimaryDark: Color = Color(0xFF381E72),
    val primaryContainerDark: Color = Color(0xFF4F378B),
    val onPrimaryContainerDark: Color = Color(0xFFEADDFF),
    val secondaryDark: Color = Color(0xFFCCC2DC),
    val onSecondaryDark: Color = Color(0xFF332D41),
    val secondaryContainerDark: Color = Color(0xFF4A4458),
    val onSecondaryContainerDark: Color = Color(0xFFE8DEF8),
    val tertiaryDark: Color = Color(0xFFEFB8C8),
    val onTertiaryDark: Color = Color(0xFF492532),
    val tertiaryContainerDark: Color = Color(0xFF633B48),
    val onTertiaryContainerDark: Color = Color(0xFFFFD8E4),
    val errorDark: Color = Color(0xFFF2B8B5),
    val onErrorDark: Color = Color(0xFF601410),
    val errorContainerDark: Color = Color(0xFF8C1D18),
    val onErrorContainerDark: Color = Color(0xFFF9DEDC),
    val backgroundDark: Color = Color(0xFF1C1B1F),
    val onBackgroundDark: Color = Color(0xFFE6E1E5),
    val surfaceDark: Color = Color(0xFF1C1B1F),
    val onSurfaceDark: Color = Color(0xFFE6E1E5),
    val surfaceVariantDark: Color = Color(0xFF49454F),
    val onSurfaceVariantDark: Color = Color(0xFFCAC4D0),
    val outlineDark: Color = Color(0xFF938F99),
    val scrimDark: Color = Color(0xFF000000),
) {
    fun toMaterialColorScheme(isDark: Boolean) = if (isDark) darkColorPalette else lightColorPalette

    private val lightColorPalette =
        lightColorScheme(
            primary = primary,
            onPrimary = onPrimary,
            primaryContainer = primaryContainer,
            onPrimaryContainer = onPrimaryContainer,
            secondary = secondary,
            onSecondary = onSecondary,
            secondaryContainer = secondaryContainer,
            onSecondaryContainer = onSecondaryContainer,
            tertiary = tertiary,
            onTertiary = onTertiary,
            tertiaryContainer = tertiaryContainer,
            onTertiaryContainer = onTertiaryContainer,
            error = error,
            onError = onError,
            errorContainer = errorContainer,
            onErrorContainer = onErrorContainer,
            background = background,
            onBackground = onBackground,
            surface = surface,
            onSurface = onSurface,
            surfaceVariant = surfaceVariant,
            onSurfaceVariant = onSurfaceVariant,
            outline = outline,
            scrim = scrim,
        )

    private val darkColorPalette =
        darkColorScheme(
            primary = primaryDark,
            onPrimary = onPrimaryDark,
            primaryContainer = primaryContainerDark,
            onPrimaryContainer = onPrimaryContainerDark,
            secondary = secondaryDark,
            onSecondary = onSecondaryDark,
            secondaryContainer = secondaryContainerDark,
            onSecondaryContainer = onSecondaryContainerDark,
            tertiary = tertiaryDark,
            onTertiary = onTertiaryDark,
            tertiaryContainer = tertiaryContainerDark,
            onTertiaryContainer = onTertiaryContainerDark,
            error = errorDark,
            onError = onErrorDark,
            errorContainer = errorContainerDark,
            onErrorContainer = onErrorContainerDark,
            background = backgroundDark,
            onBackground = onBackgroundDark,
            surface = surfaceDark,
            onSurface = onSurfaceDark,
            surfaceVariant = surfaceVariantDark,
            onSurfaceVariant = onSurfaceVariantDark,
            outline = outlineDark,
            scrim = scrimDark,
        )
}
