name: Labeling 🏷️

on:
  pull_request:
    types: [ synchronize, opened, reopened ]

jobs:
  labeling:
    name: Adding Labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Labeling
        uses: hopeman15/labelicious@0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
